# Generated by Django 5.1.2 on 2024-10-18 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Guruh ',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.CharField(max_length=255)),
                ('variant_a', models.CharField(max_length=255)),
                ('variant_b', models.CharField(max_length=255)),
                ('variant_c', models.CharField(max_length=255)),
                ('variant_d', models.CharField(max_length=255)),
                ('right_variant', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Test ',
                'verbose_name_plural': 'Testlar',
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Mavzu ',
                'verbose_name_plural': 'Mavzular',
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='TGUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_panel.group')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram bot foydalanuvchi ',
                'verbose_name_plural': 'Telegram bot foydalanuvchilari',
                'db_table': 'tg_users',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_count', models.IntegerField()),
                ('total_percent', models.FloatField()),
                ('test_right_variants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_variant_results', to='test_panel.test')),
                ('test_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_topic_results', to='test_panel.test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_panel.tgusers')),
            ],
            options={
                'verbose_name': 'Natija ',
                'verbose_name_plural': 'Natijalar',
                'db_table': 'results',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_panel.topic'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidio_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vd_name', models.CharField(max_length=255)),
                ('vd_description', models.TextField()),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_panel.group')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_panel.topic')),
            ],
            options={
                'verbose_name': 'Dars ',
                'verbose_name_plural': 'Darslar',
                'db_table': 'lessons',
            },
        ),
    ]
